plugins {
    id 'groovy'
    id 'maven-publish'
}

publishing {
    publications {
        plugin(MavenPublication) {
            from components.java
            group 'com.chenyihong.plugin'
            artifactId 'processing-flavor'
            version '1.0.1'
        }
    }
}

dependencies {
    implementation(gradleApi())
    // 网络请求
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    // 解析Excel
    implementation("net.sourceforge.jexcelapi:jxl:2.6.12")
    // 解析xml
    implementation("org.dom4j:dom4j:2.1.4")
}